#!/usr/bin/env python
from platform import platform


def get_platform():
    system_platform = platform().lower()
    if "darwin" in system_platform:
        operating_system = "mac"
    elif "win" in system_platform:
        operating_system = "windows"
    elif "linux" in system_platform:
        operating_system = "linux"
    return operating_system

def main():
    operating_system = get_platform()
    print(operating_system)


if __name__ == "__main__":
    main()
