#!/usr/bin/zsh

#Determines the Operating System
script_path="$HOME/DevEnv/scripts/get_os"
operating_system=$($script_path)


if [[ $operating_system == "windows" ]]; then
    echo "Loading Windows Functions"
elif [[ $operating_system == "linux" ]]; then
    echo "Loading Linux Functions"
else
    echo "Loading Mac Functions"
fi
