#!/usr/bin/env zsh

#Determines the Operating System
export DEVENV="$HOME/DevEnv"
script_path="$DEVENV/scripts/get_os"
operating_system=$($script_path)


if [[ $operating_system == "windows" ]]; then
    export DEVENV_PATH="$DEVENV/Windows"
elif [[ $operating_system == "linux" ]]; then
    export DEVENV_PATH="$DEVENV/Linux"
elif [[ $operating_system == "mac" ]]; then
    export DEVENV_PATH="$DEVENV/Mac"
fi
